version: '3.6'

services:
  postgres:
    build: ./postgres
    ports:
      - "6666:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    volumes:
      - "${POSTGRES_LOCAL_DIR}:/var/lib/postgresql/data"
      - ./postgres/sql/:/sql/
