version: '3.6'

services:
  postgres:
    image: postgres:10
    ports:
      - "6666:5432"
    environment:
      - POSTGRES_USER=nasdaq_scraper
      - POSTGRES_DB=nasdaq_scraper
      - POSTGRES_PASSWORD=nasdaq_scraper
    volumes:
      - /var/local/docker/postgres/nasdaq_scraper:/var/lib/postgresql/data

  scraper:
    build: .
    environment:
      - POSTGRES_USER=nasdaq_scraper
      - POSTGRES_DB=nasdaq_scraper
      - POSTGRES_PASSWORD=nasdaq_scraper
      - POSTGRES_HOST=postgres
      - TICKERS_FILE=/var/input/tickers.txt
    depends_on:
      - postgres
    volumes:
      - ./nasdaq_analytics:/srv/project_x/nasdaq_analytics
      - ./migrations:/srv/project_x/migrations
      - ./docs:/srv/project_x/docs
      - ./input_example:/var/input
    command: ./nasdaq_analytics/scraper.sh

  web:
    build: .
    environment:
      - POSTGRES_USER=nasdaq_scraper
      - POSTGRES_DB=nasdaq_scraper
      - POSTGRES_PASSWORD=nasdaq_scraper
      - POSTGRES_HOST=postgres
      - FLASK_APP=nasdaq_analytics/web
      - FLASK_ENV=development
      - FLASK_RUN_PORT=8080
    depends_on:
      - postgres
    volumes:
      - ./nasdaq_analytics:/srv/project_x/nasdaq_analytics
      - ./migrations:/srv/project_x/migrations
    ports:
      - 8080:8080
    command: flask run --host=0.0.0.0
